### ISSUE TITLE
Port to Ruby ?

### ISSUE THREAD

**Issue by dchelimsky** [Chicago/metalicious#28]
I think there might be more developer support in Chicago if this were written in Ruby. What do other contributors (existing and potential) think? Anybody reading this who would like to contribute and would prefer to work in Ruby?

**Comment by derekeder** [comment]
years later, I realize that I did not apply the term 'yak shaving' properly in this context. still, it was not a good idea to rewrite an entire codebase.

anyways, RIP metalicious. it was a beautiful dream
